import { siteConfig } from "./site";

export type LegalSection = { title: string; paragraphs?: string[]; bullets?: string[] };

export const privacySections: LegalSection[] = [
  { title: "Information Cyla processes", paragraphs: ["Depending on what you choose to enter, Cyla may process period start and end dates, cycle length, symptoms, mood, flow, energy, notes, and preferences or settings. This information can be personal and sensitive in nature."] },
  { title: "Local-first storage", paragraphs: ["Cyla does not require an account. In the current version, cycle entries are intended to be stored locally on your device using Apple’s native storage technologies. Cyla does not operate a backend database containing menstrual entries in the current version.", "If future versions introduce backup, syncing, sharing, or other data features, we will explain those changes before or when they become available and update this Policy." ] },
  { title: "We do not sell your data", paragraphs: ["We do not sell your personal or cycle data."] },
  { title: "Website data and analytics", paragraphs: ["When you visit cylaapp.com, hosting and infrastructure providers may handle ordinary technical information such as your IP address, browser or device information, request logs, and security logs.", "This website uses DataFast to measure page visits and navigation. DataFast may process technical information such as page URLs, browser and device information, referrer information, and persistent visitor or session identifiers stored in your browser. Cyla does not intentionally send cycle entries, symptoms, moods, notes, or other menstrual history to DataFast.", "Cyla also uses DataFast server-side bot traffic tracking for requests that appear to come from known crawlers. For those requests, DataFast may process the requested URL, user-agent, and source IP to classify crawler traffic. This is not intended to track ordinary human browsing."] },
  { title: "Apple", paragraphs: ["Downloads, App Store transactions, and some device or platform functionality are provided by Apple. Apple’s handling of information is governed by its own privacy practices. Apple does not endorse Cyla simply because Cyla is available through the App Store."] },
  { title: "Why information is used", bullets: ["to provide cycle tracking and estimated cycle predictions", "to save your preferences", "to operate and improve the app", "to provide purchases if they are introduced", "to prevent abuse and security issues", "to comply with legal obligations"] },
  { title: "Predictions and health information", paragraphs: ["Cyla’s cycle predictions are estimates based on the information you provide. Cyla is not a medical device and does not provide medical diagnosis, treatment, or medical advice.", "Cyla must not be relied upon as contraception."] },
  { title: "Data retention", paragraphs: ["Locally stored Cyla data remains on your device until you delete it through the app, remove the app or device storage, or it is deleted through another platform-level action. Server-side technical records, where they exist for the website or service operations, are retained only as reasonably necessary for operations, security, legal obligations, or dispute resolution."] },
  { title: "Your choices and rights", paragraphs: ["You can review information available in the app, correct or delete entries, and delete locally stored Cyla data through the app or by removing the app’s storage from your device. You may also contact us about privacy questions or rights available to you under applicable law, including Indian data-protection law where it applies. Because cycle entries are local in the current version, we may not have a copy to access, correct, or delete for you." ] },
  { title: "Security", paragraphs: ["Reasonable measures are used to protect information within the scope of the current service. No method of electronic storage or transmission can be guaranteed to be 100% secure."] },
  { title: "Children", paragraphs: ["Cyla is intended for users legally permitted to use the service. If a user is below the age at which parental or guardian consent is legally required, they may use Cyla only with appropriate consent. This is particularly important where applicable law requires verifiable parental or guardian consent for a child’s personal data."] },
  { title: "International services", paragraphs: ["Apple, hosting providers, and other service providers used in the future may process technical information outside India where applicable. Their processing is subject to their own infrastructure, terms, and applicable law."] },
  { title: "Changes to this Policy", paragraphs: ["We may update this Privacy Policy as Cyla evolves or as legal requirements change. The Last updated date above will reflect material updates."] },
  { title: "Contact", paragraphs: [`Privacy questions: ${siteConfig.supportEmail}`] },
];

export const termsSections: LegalSection[] = [
  { title: "Acceptance", paragraphs: ["By downloading, accessing, or using Cyla, you agree to these Terms. If you do not agree, do not use the service."] },
  { title: "What Cyla does", bullets: ["log menstrual cycles", "view estimated future periods", "record symptoms and related information", "view general personal cycle insights"] },
  { title: "Not medical advice", paragraphs: ["Cyla is provided for informational and personal tracking purposes only. It is not a medical service, medical device, diagnosis tool, treatment service, or substitute for advice from a qualified healthcare professional.", "Cyla should not be used for emergency medical decisions or relied upon as contraception or a method for preventing pregnancy. If you have concerns about your health, cycle, symptoms, pregnancy, fertility, or medication, consult an appropriate healthcare professional."] },
  { title: "Predictions are estimates", paragraphs: ["Menstrual cycles can vary. Predictions may be early or late, and historical information does not guarantee future dates. Cyla does not guarantee the accuracy of its predictions."] },
  { title: "Your responsibility", bullets: ["the information you enter", "decisions you make based on that information", "maintaining access to and security of your device", "keeping information accurate if you want better estimates"] },
  { title: "Availability and changes", paragraphs: ["We may modify, fix, remove, discontinue, or change features and functionality as Cyla evolves. We do not guarantee permanent, uninterrupted, or error-free availability."] },
  { title: "Acceptable use", paragraphs: ["Do not misuse or interfere with Cyla; attempt unauthorised access; exploit vulnerabilities; impersonate others; use the service unlawfully; or use automated systems to attack the service. Do not reverse engineer Cyla where prohibited, subject to applicable law."] },
  { title: "Intellectual property", paragraphs: ["The Cyla name, logo, interface, website, source content, and original design and content belong to Divv Saxena or applicable licensors, except for third-party technologies and assets. We grant you a limited, personal, non-transferable right to use Cyla in accordance with these Terms. You retain rights in your personal information."] },
  { title: "Third-party services", paragraphs: ["Cyla is distributed through Apple’s App Store. Apple and any third-party services introduced in future versions have their own terms and privacy practices. Their use is subject to those terms where applicable."] },
  { title: "Purchases", paragraphs: ["Cyla V1 is currently intended to be free. If paid features, subscriptions, or in-app purchases are introduced, purchases made through the App Store will generally be processed by Apple and subject to Apple’s applicable purchase, billing, cancellation, and refund rules."] },
  { title: "Disclaimer of warranties", paragraphs: ["To the maximum extent allowed by applicable law, Cyla is provided “as is” and “as available.” We do not guarantee uninterrupted availability, perfect accuracy, error-free predictions, or suitability for a particular medical purpose."] },
  { title: "Limitation of liability", paragraphs: ["To the maximum extent permitted by applicable law, Divv Saxena will not be liable for indirect, incidental, special, or consequential losses arising from use of or inability to use Cyla. Cyla should not be relied upon for medical or contraceptive decisions.", "Nothing in these Terms excludes or limits liability that cannot lawfully be excluded under applicable law."] },
  { title: "Indemnity", paragraphs: ["To the extent permitted by law, you are responsible for losses caused by your unlawful misuse of Cyla or your violation of these Terms."] },
  { title: "Governing law", paragraphs: ["These Terms are governed by the laws of India, without prejudice to any mandatory consumer rights that may apply. Courts of competent jurisdiction in India will have jurisdiction, subject to applicable law."] },
  { title: "Apple App Store", paragraphs: ["These Terms are between you and Cyla / Divv Saxena, not Apple. Apple is not responsible for operating or supporting Cyla except as required by its own policies. Use through Apple’s platform is also subject to applicable App Store terms."] },
  { title: "Changes to these Terms", paragraphs: ["We may update these Terms as Cyla evolves. Material changes will update the Last updated date above."] },
  { title: "Contact", paragraphs: [`Questions: ${siteConfig.supportEmail}`] },
];
